version: "3.8"

services:
  ml-backend:
    container_name: ml-backend
    image: hi-algo/label-studio-ml-sam2:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   target: production
    #   args:
    #     TEST_ENV: ${TEST_ENV}

    #    deploy:
    #      resources:
    #        reservations:
    #          devices:
    #            - driver: nvidia
    #              count: 1
    #              capabilities: [ gpu ]


    environment:
      # specify these parameters if you want to use basic auth for the model server
      - BASIC_AUTH_USER=hi-algo
      - BASIC_AUTH_PASS=hi-algo-2026
      # set the log level for the model server
      - LOG_LEVEL=WARNING
      # any other parameters that you want to pass to the model server
      - ANY=PARAMETER
      # specify the number of workers and threads for the model server
      - WORKERS=4
      - THREADS=8
      # specify the model directory (likely you don't need to change this)
      - MODEL_DIR=/data/models
      # specify device
      - DEVICE=cuda # or 'cpu' (coming soon)
      # SAM2 model config
      - MODEL_CONFIG=configs/sam2/sam2.1_hiera_l.yaml
      # SAM2 checkpoint
      - MODEL_CHECKPOINT=sam2.1_hiera_large.pt

      # Specify the Label Studio URL and API key to access
      # uploaded, local storage and cloud storage files.
      # Do not use 'localhost' as it does not work within Docker containers.
      # Use prefix 'http://' or 'https://' for the URL always.
      # Determine the actual IP using 'ifconfig' (Linux/Mac) or 'ipconfig' (Windows).
      - LABEL_STUDIO_URL=http://10.220.176.94:8080
      - LABEL_STUDIO_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6ODA3NjA3MzgyMSwiaWF0IjoxNzY4ODczODIxLCJqdGkiOiJkODRjZmVlYjBlNTU0OTZiYTM0NGVkMGU5YTEzZmY5OSIsInVzZXJfaWQiOiIxIn0.BRWz1bAq3dcwxBDUy_ymUsHH8aWuNKkawrKWB_IzAiE
    ports:
      - "9090:9090"
    volumes:
      - "./ml-backend:/data"
    restart: unless-stopped  # 生产环境建议添加自动重启